const EMPTY_CELL_VALUE = 0;
const WOLF_VALUE = 1;
const RABBIT_VALUE = 2;
const WALL_VALUE = 3;
const HOME_VALUE = 4;
const DIE_VALUE = 66;
const WIN_VALUE = 88;
const RABBIT_COUNT = 1;
const HOME_COUNT = 1;
const WOLF_COUNT = 5;
const WALL_COUNT = 5;
const X = 0;
const Y = 1;
const matrixSize = 10;
const side = 60;
let rabbit;
let matrix = [];
let wolfArr = [];
let ImgUrls = {};
let rabbitImg, homeImg, wolfImg, wallImg, dieImg, winImg;